// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEt9VGLRDVEAQ7vmGoH2-7ae2Qe1UelEQ',
    appId: '1:653232549008:web:4e3bbf00d5b9a422327c15',
    messagingSenderId: '653232549008',
    projectId: 'padel-d8e9d',
    authDomain: 'padel-d8e9d.firebaseapp.com',
    storageBucket: 'padel-d8e9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5sRW9UnmtGq8mgI-TVQ7KZ8WDufjTGs',
    appId: '1:653232549008:android:a3aea28260ba75a2327c15',
    messagingSenderId: '653232549008',
    projectId: 'padel-d8e9d',
    storageBucket: 'padel-d8e9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6keTJpldG4XRYHlg1vRTXhZGLXXtOWQU',
    appId: '1:653232549008:ios:a21910b7eeff2760327c15',
    messagingSenderId: '653232549008',
    projectId: 'padel-d8e9d',
    storageBucket: 'padel-d8e9d.appspot.com',
    iosClientId: '653232549008-1v8i9qslbagel0hs8bqhv7queqtlqp6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.padel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6keTJpldG4XRYHlg1vRTXhZGLXXtOWQU',
    appId: '1:653232549008:ios:a21910b7eeff2760327c15',
    messagingSenderId: '653232549008',
    projectId: 'padel-d8e9d',
    storageBucket: 'padel-d8e9d.appspot.com',
    iosClientId: '653232549008-1v8i9qslbagel0hs8bqhv7queqtlqp6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.padel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEt9VGLRDVEAQ7vmGoH2-7ae2Qe1UelEQ',
    appId: '1:653232549008:web:d75b24e0b6810154327c15',
    messagingSenderId: '653232549008',
    projectId: 'padel-d8e9d',
    authDomain: 'padel-d8e9d.firebaseapp.com',
    storageBucket: 'padel-d8e9d.appspot.com',
  );
}
